version: '3.8'

services:
  next-app-dev:
    build:
      context: .
      dockerfile: Dockerfile_dev
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      # Прокидаємо код всередину контейнера, щоб Next.js міг реагувати на зміни (HMR)
      - .:/app
      # Окремий volume для node_modules, щоб не перезаписувати встановлені в контейнері залежності локальними
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
      # Додаємо AUTH_TRUST_HOST, щоб уникнути помилок 'UntrustedHost' в Docker
      - AUTH_TRUST_HOST=true
    env_file:
      - .env
    user: "1001:1001" # Запуск від користувача nextjs
