version: '3.8'

services:
  next-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      # Додаємо AUTH_TRUST_HOST, щоб уникнути помилок 'UntrustedHost' в Docker
      - AUTH_TRUST_HOST=true
    env_file:
      - .env
    restart: unless-stopped
