FROM node:24-alpine

RUN apk add --no-cache git mc libc6-compat

WORKDIR /app

ENV NODE_ENV=development

# Create user with matching ID to avoid permission issues when mapping volumes
RUN addgroup -g 1001 -S nodejs && \
    adduser -u 1001 -S nextjs -G nodejs

# Give ownership of /app to nextjs user
RUN chown -R nextjs:nodejs /app

USER nextjs

ARG PORT=3000
ENV PORT=${PORT}

EXPOSE ${PORT}

# Start script will just keep container alive if needed or run dev server
CMD ["npm", "run", "dev"]
